const CONTROL_LABELS: Record<string, string> = {
  level: 'LEVEL',
  tone: 'TONE',
  attack: 'ATTACK',
  sustain: 'SUSTAIN',
  threshold: 'THRESH',
  release: 'RELEASE',
  gain: 'GAIN',
  distortion: 'DIST',
  filter: 'FILTER',
  volume: 'VOL',
  mids: 'MIDS',
  gate: 'GATE',
  low: 'LOW',
  high: 'HIGH',
  rate: 'RATE',
  depth: 'DEPTH',
  res: 'RES',
  mix: 'MIX',
  manual: 'MANUAL',
  rise: 'RISE',
  wave: 'WAVE',
  cents: 'CENTS',
  blend: 'BLEND',
  spread: 'SPREAD',
  time: 'TIME',
  feedback: 'FDBK',
  mod: 'MOD',
  repeats: 'REPEATS',
  wow: 'WOW',
  width: 'WIDTH',
  decay: 'DECAY',
  preDelay: 'PRE-DLY',
  lowCut: 'LOW CUT',
  highCut: 'HIGH CUT',
  density: 'DENSITY',
  hold: 'HOLD',
  motion: 'MOTION',
  '100': '100',
  '200': '200',
  '400': '400',
  '800': '800',
  '1600': '1.6K',
  '3200': '3.2K',
  '6400': '6.4K',
};

export function getPedalControlLabel(effectId: string, controlId: string) {
  if (effectId === 'studio-comp' && controlId === 'sustain') return 'SENS';
  const label = CONTROL_LABELS[controlId];
  if (!label) throw new Error(`Missing pedal control label for ${effectId}.${controlId}`);
  return label;
}
